Export Consent Forms (Markdown)
StanfordSpezi/SpeziTemplateApplication pull request #40
Opened 2023-10-03 21:39 UTC by philippzagar

# *Export Consent Forms (Markdown)*

## :recycle: Current situation & Problem
*Link any open issues or pull requests (PRs) related to this PR. Please ensure that all non-trivial PRs are first tracked and discussed in an existing GitHub issue or discussion.*

## :gear: Release Notes 
*Add a bullet point list summary of the feature and possible migration guides if this is a breaking change so this section can be added to the release notes.*
*Include code snippets that provide examples of the feature implemented or links to the documentation if it appends or changes the public interface.*

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
*You can use this section to describe your solution, but we encourage contributors to document your reasoning and changes using in-line documentation.* 

## :white_check_mark: Testing
*Please ensure that the PR meets the testing requirements set by CodeCov and that new functionality is appropriately tested.*
*This section describes important information about the tests and why some elements might not be testable.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2023-10-03 21:51 UTC, philippzagar commented
@PSchmiedmayer PR ready for review, keep in mind that the `feat/export-consent-forms` branch of `SpeziOnboarding` is currently set as a dependency so that you are able to test locally / Pipeline succeeds. As soon as https://github.com/StanfordSpezi/SpeziOnboarding/pull/26 is merged and tagged, I'll update the dependency to a tagged version.

2023-10-03 22:05 UTC, philippzagar commented
@PSchmiedmayer Seems like the pipeline is running into some issues:
```
Error: Encountered a fatal error while running "/Users/runner/hostedtoolcache/CodeQL/2.14.6/x64/codeql/codeql database finalize --finalize-dataset --threads=4 --ram=13004
/Users/runner/work/SpeziTemplateApplication/SpeziTemplateApplication/.codeql/swift". 
Exit code was 32 and error was: CodeQL detected code written in Swift but could not process any of it. Review our troubleshooting guide at https://gh.io/troubleshooting-code-scanning/no-source-code-seen-during-build.
```

2023-10-04 06:49 UTC, PSchmiedmayer commented
@philippzagar Thank you for the PR. I will give https://github.com/StanfordSpezi/SpeziOnboarding/pull/26 a review and then we can merge this one here. Also took a look at the build errors in #39 & #41, that should also fix the CI in this PR 👍

2023-10-10 19:46 UTC, philippzagar commented
@PSchmiedmayer Ready for review after you reviewed https://github.com/StanfordSpezi/SpeziOnboarding/pull/26 :)

2023-10-11 23:19 UTC, PSchmiedmayer requested changes
Thank you for the great additions, looking forward to see this PR being merged!

I had a small comment regarding the functionality to upload the consent document to Firebase Cloud Storage. Apart from this the PR looks great and the code is well structured 🚀

2023-10-11 23:19 UTC, PSchmiedmayer commented on TemplateApplication/TemplateApplicationStandard.swift
> +        consent.write(to: filePath)
I think this is a great behavior if we have disable the Firebase interaction. I think the Firebase behaviour should be uploading the PDF to firebase in e.g. the firebase cloud storage: https://firebase.google.com/docs/storage

2023-10-12 19:48 UTC, philippzagar commented
Note to ourselves: We need to merge https://github.com/StanfordSpezi/SpeziFirebase/pull/17 first and adjust the dependencies within this branch

2023-10-14 18:54 UTC, PSchmiedmayer approved these changes
Nice, thank you for the changes; looks great and happy to merge it once we have the related PRs merged and ready 👍

2023-10-14 18:54 UTC, PSchmiedmayer commented on TemplateApplication.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "revision" : "e8f178eee45830f75081d3bd4b291881fee5d7c9"
Just a conversation to remind us that we have to remove that before merging the PR.

2023-10-14 18:54 UTC, PSchmiedmayer commented on TemplateApplication.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "revision" : "9b9f362c95c807902a0b7f7bbf1ded238f84748b"
Just a conversation to remind us that we have to remove that before merging the PR.

2023-10-16 06:43 UTC, merged